package tictactoe;

import java.util.Random;

/**
 *
 * @author Iwonkxx
 */
public class TicTacToe extends javax.swing.JFrame {
    
    private final String o = "O";
    private final String x = "X";
    private int currentPlayer;

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 110));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 13, 120, 110));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 163, 120, 150));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 170, 150));

        jButton6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 153, 120, 160));

        jButton7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setDefaultCapable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 353, 110, 140));

        jButton8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 353, 170, 140));

        jButton9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setDefaultCapable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 120, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/tictactoe.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton10.setText("Acak");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 120, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 90, 170, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton4.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton4.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton4.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton8.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton8.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton8.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        currentPlayer = random.nextInt(2);
        if (currentPlayer == 0) {
            jLabel1.setText("Giliran Player 1");
        } else {
            jLabel1.setText("Giliran Player 2");
        }
        acak();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton1.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton1.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton1.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton2.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton2.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton2.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton3.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton3.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton3.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton5.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton5.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton5.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton6.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton6.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton6.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton7.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton7.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton7.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (currentPlayer == 0) {
            jButton9.setText(o);
            currentPlayer = 1;
            jLabel1.setText("Giliran Player 2");
        } else {
            jButton9.setText(x);
            currentPlayer = 0;
            jLabel1.setText("Giliran Player 1");
        }
        jButton9.setEnabled(false);
        endGame();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void acak() {
        jButton10.setEnabled(false);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
    }
    
    private void win() {
        if ((jButton1.getText().equals(o) && jButton2.getText().equals(o) &&
                jButton3.getText().equals(o)) || (jButton1.getText().equals(o) && 
                jButton4.getText().equals(o) && jButton7.getText().equals(o)) ||
                (jButton1.getText().equals(o) && jButton5.getText().equals(o) &&
                jButton9.getText().equals(o)) || (jButton2.getText().equals(o) && 
                jButton5.getText().equals(o) && jButton8.getText().equals(o)) ||
                (jButton3.getText().equals(o) && jButton6.getText().equals(o) &&
                jButton9.getText().equals(o)) || (jButton4.getText().equals(o) && 
                jButton5.getText().equals(o) && jButton6.getText().equals(o)) ||
                (jButton7.getText().equals(o) && jButton8.getText().equals(o) &&
                jButton9.getText().equals(o)) || (jButton3.getText().equals(o) && 
                jButton5.getText().equals(o) && jButton7.getText().equals(o))) {
            jLabel1.setText("Player 1 Win!");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        } else if ((jButton1.getText().equals(x) && jButton2.getText().equals(x) &&
                jButton3.getText().equals(x)) || (jButton1.getText().equals(x) && 
                jButton4.getText().equals(x) && jButton7.getText().equals(x)) ||
                (jButton1.getText().equals(x) && jButton5.getText().equals(x) &&
                jButton9.getText().equals(x)) || (jButton2.getText().equals(x) && 
                jButton5.getText().equals(x) && jButton8.getText().equals(x)) ||
                (jButton3.getText().equals(x) && jButton6.getText().equals(x) &&
                jButton9.getText().equals(x)) || (jButton4.getText().equals(x) && 
                jButton5.getText().equals(x) && jButton6.getText().equals(x)) ||
                (jButton7.getText().equals(x) && jButton8.getText().equals(x) &&
                jButton9.getText().equals(x)) || (jButton3.getText().equals(x) && 
                jButton5.getText().equals(x) && jButton7.getText().equals(x))) {
            jLabel1.setText("Player 2 Win!");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        } else  if (!jButton1.isEnabled() && !jButton2.isEnabled() && !jButton3.isEnabled()
                && !jButton4.isEnabled() && !jButton5.isEnabled() && !jButton6.isEnabled()
                && !jButton7.isEnabled() && !jButton8.isEnabled() && !jButton9.isEnabled()) {
            jLabel1.setText("Seri!");
            jButton10.setEnabled(true);
        }
    }
    
    private void endGame() {
        if (!jButton1.isEnabled() || !jButton2.isEnabled() || !jButton3.isEnabled()
                || !jButton4.isEnabled() || !jButton5.isEnabled() || !jButton6.isEnabled()
                || !jButton7.isEnabled() || !jButton8.isEnabled() || !jButton9.isEnabled()) {
            win();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
